### ISSUE TITLE
Add some common patterns of failure caused by model rollouts

### ISSUE THREAD

**Issue by visenger** [xLaszlo/datascience-fails#1]
Hi @xLaszlo, 

here we go with the first issue 😃 

In the following article https://www.oreilly.com/content/a-brief-guide-to-running-ml-systems-in-production/ you will find a section about common patterns of failure caused by model rollouts.

The whole article is though an interesting read (googles SRE perspective on running ML systems in production).

Kind regards,
Larysa

**Comment by xLaszlo** [comment]
in
