### ISSUE TITLE
Add "Managing the Risks of Adopting AI Engineering"

### ISSUE THREAD

**Issue by visenger** [xLaszlo/datascience-fails#3]
From the article: https://insights.sei.cmu.edu/sei_blog/2020/08/managing-the-risks-of-adopting-ai-engineering.html

Organizations that adopt AI often encounter the following risk conditions:

- ill-defined problem statement
- lack of expertise
- model-system-data disconnection
- unrealistic expectations
- data challenges
- lack of verifiability

**Comment by xLaszlo** [comment]
Good one, especially that the bullets are written already.
